version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    network_mode: bridge

  admin:
    build: ./admin
    links:
      - db
    network_mode: bridge

  client:
    build: ./client
    links:
      - app
    network_mode: bridge

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    network_mode: bridge
